### ISSUE TITLE
/login 로그인 화면 구성

### ISSUE THREAD

**Issue by hsj2955** [teamblend3/blend-dta-client#11]
## Server API
`GET` [`/api/users/login`](https://github.com/teamblend3/blend-dta-server/issues/5#issue-2104917408)

## TODO
- [x] 구글 소셜 로그인 버튼이 보여져야 한다.
- [x] 로그인 버튼 클릭 시, 구글 소셜 로그인 모달창을 보여주어야 한다.
- [x] 로그인에 성공할 시, /projects 로 이동해야 한다.
- [x] Test 파일을 작성해야 한다.
