### ISSUE TITLE
/projects/:projectId 화면 구성(Data Preview)

### ISSUE THREAD

**Issue by jwbaeck** [teamblend3/blend-dta-client#12]
## UI
<img width="1025" alt="스크린샷 2024-01-31 오후 8 01 59" src="https://github.com/teamblend3/blend-dta-client/assets/99715151/99088950-fbae-4420-bd5b-90de0c205a7d">

## Server API
`GET` [`/api/projects/:projectId`](https://github.com/teamblend3/blend-dta-server/issues/9#issue-2104927968)

## TODO
- [x] 해당 Collection 데이터 내용을 문자열로 확인할 수 있는 Data Preview 가 보여져야 한다.
- [x] 해당 Collection 생성 날짜와 업데이트 된 날짜를 확인할 수 있는 리스트가 보여져야 한다.
- [x] 사용자가 Google Spread Sheet 에서 데이터를 수정 후 새로고침 버튼을 클릭 시, 사용자의 수정 내용을 바탕으로 위 2개의 리스트 내용또한 그에 맞게 변경되어야 한다.
- [ ] Test 파일을 작성해야 한다.
