### ISSUE TITLE
/projects 화면 구성(Before Sync)

### ISSUE THREAD

**Issue by hsj2955** [teamblend3/blend-dta-client#13]
## UI
<img width="1021" alt="스크린샷 2024-01-31 오후 7 30 32" src="https://github.com/teamblend3/blend-dta-client/assets/99715151/506176f7-c06a-4109-872f-7a6bdbd854cd">
<img width="1024" alt="스크린샷 2024-01-31 오후 7 14 53" src="https://github.com/teamblend3/blend-dta-client/assets/99715151/62cfd81d-9d91-42a5-bb2c-8e96b75dedf2">
<br/>

## Server API
`GET` [`/api/users/{id}/projects`](https://github.com/teamblend3/blend-dta-server/issues/8#issue-2104921550)

## TODO
- [x] 헤더 우측에는 프로필 이미지를 보여주어야 한다.
- [x] 헤더의 프로필 이미지를 hover 할 경우, profile, projects, log out 버튼을 클릭할 수 있는 팝업창을 보여주어야 한다.
- [x] 메인페이지 우측 상단에는 내 Project 를 생성할 수 있는 Button 이 존재해야 한다.
- [x] 내 Project의 목록을 확인할 수 있는 리스트가 보여져야 한다.
- [x] Project 리스트는 Project Name, Project 에 포함된 collection 의 개수, Project 생성 날짜의 정보를 포함해야 한다.
- [x] MongoDB & Google Spread Sheet 동기화 이전에는 Projects 데이터가 리스트에 표시될 수 없다.
- [x] Test 파일을 작성해야 한다.

## TEST CODE

- [x] 응답받은 projects의 개수가 5행을 넘을 경우 페이지네이션이 활성화 되어야 한다.
- [x] 응답받은 projects의 개수가 없을때는 "projects가 비어있습니다." 라는 코멘트가 보여야 한다.
