### ISSUE TITLE
/projects/new 화면 구성(Sync)

### ISSUE THREAD

**Issue by jwbaeck** [teamblend3/blend-dta-client#16]
## UI
<img width="1023" alt="스크린샷 2024-01-31 오후 7 39 47" src="https://github.com/teamblend3/blend-dta-client/assets/99715151/03fb6734-ea3e-4069-9dbc-420568d33f85">
<img width="1022" alt="스크린샷 2024-01-31 오후 7 40 51" src="https://github.com/teamblend3/blend-dta-client/assets/99715151/47a25ab7-e35c-498f-84b1-769feec2acfe">
<img width="1022" alt="스크린샷 2024-01-31 오후 7 41 22" src="https://github.com/teamblend3/blend-dta-client/assets/99715151/0fd66753-ca2c-4ed5-aad7-b3f2f4d0b89a">

### Before Sync
<img width="1023" alt="스크린샷 2024-01-31 오후 7 44 54" src="https://github.com/teamblend3/blend-dta-client/assets/99715151/87da954c-f7f2-4f5f-8bb8-2b996026b655">

### After Sync
<img width="1025" alt="스크린샷 2024-01-31 오후 7 45 17" src="https://github.com/teamblend3/blend-dta-client/assets/99715151/4fe00204-4a64-4bbf-a430-410488587335">

## Server API
`POST` [`/api/projects/new`](https://github.com/teamblend3/blend-dta-server/issues/7#issue-2104920003)

## TODO
- [x] 사용자의 MongoDB 와 Google Spread Sheet 의 연동을 시작하는 버튼이 보여져야 한다.
- [x] 연동이 진행 중일 경우, Loading Component 를 모달창을 통해 보여주어야 한다.
- [x] 연동에 성공할 경우, 모달창에 연동이 성공했다는 메세지가 보여져야 한다.
- [x] 모달창에 Project List 페이지(/projects) 혹은 사용자의 Google Spread Sheet URL 주소로 이동할 수 있는 버튼이 보여져야 한다.
- [x] 연동에 성공하고 본인의 Google Spread Sheet URL 로 이동 시, 사용자 MongoDB 의 데이터가 Sheet 에 작성된 상태여야 한다.
- [ ] Test 파일을 작성해야 한다.

## Loading Component
- [x] Bar로 로딩 구현에서 스텝으로 표현으로 변경
