### ISSUE TITLE
/profile 사용자 프로필 화면 구성

### ISSUE THREAD

**Issue by hsj2955** [teamblend3/blend-dta-client#17]
## UI
<img width="1024" alt="스크린샷 2024-01-31 오후 7 23 59" src="https://github.com/teamblend3/blend-dta-client/assets/99715151/0f18ea17-1863-419c-938d-70b6c22205e7">
<img width="1024" alt="스크린샷 2024-01-31 오후 7 24 38" src="https://github.com/teamblend3/blend-dta-client/assets/99715151/9d23b460-d536-4bdc-9bc1-30b52b013d99">
<img width="1024" alt="스크린샷 2024-01-31 오후 7 25 17" src="https://github.com/teamblend3/blend-dta-client/assets/99715151/302cfb85-d7d8-4a85-b674-00ebc9f5100e">
<br/>

## Server API
`GET` [`/api/users/{id}/profile`](https://github.com/teamblend3/blend-dta-server/issues/6#issue-2104919096)

## TODO
- [x] 사용자의 프로필 이미지, 사용자 이름, 사용자 이메일을 정보를 보여주어야 한다.
- [x] 사용자가 생성한 Projects List 가 보여져야 한다.
- [x] List 는 Project 제목, Project 가 포함하는 collections 개수, Project 생성 날짜 정보를 포함해야 한다.
- [x] 각 Project 클릭 시, 해당 Project 의 상세 페이지(/projects/:projectId) 로 이동할 수 있어야 한다.
- [x] Test 파일을 작성해야 한다.
