### ISSUE TITLE
/projects/new 화면 구성(Google Spread Sheet URL)

### ISSUE THREAD

**Issue by jwbaeck** [teamblend3/blend-dta-client#18]
## UI
<img width="1024" alt="스크린샷 2024-01-31 오후 7 26 10" src="https://github.com/teamblend3/blend-dta-client/assets/99715151/37032aea-f27d-404c-a4d0-5440c4d83fe7">

## Server API
`GET` [`/api/validation/sheet`](https://github.com/teamblend3/blend-dta-server/issues/11#issue-2104935885)

## TODO
- [x] 사용자는 이미 보유한 Google Spread Sheet URL 을 직접 입력할 수 있다.
- [x] 새로운 Google Spread Sheet URl 을 생성하는 버튼이 존재한다.
- [x] 사용자가 Sheet URL 을 보유하고 있지 않은 경우, 이 버튼을 클릭해서 새로운 Sheet URL 을 생성할 수 있어야 한다.
- [x] Google Spread Sheet URL 주소가 유효하지 않은 경우, 에러 메세지를 통해 표시해주어야 한다.
- [x] Test 파일을 작성해야 한다.
