### ISSUE TITLE
/projects/new 화면 구성(MongoDB URL)

### ISSUE THREAD

**Issue by hsj2955** [teamblend3/blend-dta-client#20]
## UI
<img width="1024" alt="스크린샷 2024-01-31 오후 7 26 10" src="https://github.com/teamblend3/blend-dta-client/assets/99715151/37032aea-f27d-404c-a4d0-5440c4d83fe7">

## Server API
`POST` [`/api/validation/db`](https://github.com/teamblend3/blend-dta-server/issues/17#issue-2107157653)

## TODO
- [x] 헤더에는 사용자 프로필 이미지를 보여주어야 한다.
- [x] 사용자의 MongoDB URL, MongoDB ID, MongoDB PW, MongoDB Table 이름을 각각의 입력창에 입력할 수 있어야 한다.
- [x] MongoDB URL 은 사용자의 MongoDB ID 와 PW 를 제외한 형식으로, 이 입력 양식을 사용자가 알 수 있도록 설명하는 텍스트가 있어야 한다.
- [x] 사용자 입력이 유효한 MongoDB 정보인지 확인할 수 있는 버튼이 보여져야 한다.
- [x] 유효하지 않은 입력값일 경우 텍스트를 통해 메시지를 보여줘야 한다.
- [x] Test 파일을 작성해야 한다.
