### ISSUE TITLE
Header 화면 세팅

### ISSUE THREAD

**Issue by jwbaeck** [teamblend3/blend-dta-client#22]
## TODO
- [x] 헤더 좌측에는 서비스 로고 이미지가 보여야 한다.
- [x] Login 버튼 클릭 시, 로그인 페이지(/login) 로 이동해야 한다.
- [x] Home 버튼 클릭 시, 메인 페이지(/projects) 로 이동해야 한다.
- [x] Profile Image 클릭 시, 팝업창이 보여야 한다.
- [x] 팝업창에는 Profile 페이지(/profile), Projects 페이지(/projects), Logout(/) 페이지로 이동할 수 있는 버튼이 보여져야 한다.
- [x] Profile Image 를 다시 클릭하면 팝업창이 보이지 않아야 한다.
- [x] 테스트 코드를 작성해야 한다.
