### ISSUE TITLE
초기세팅(레포 생성 & 환경 설정)

### ISSUE THREAD

**Issue by hsj2955** [teamblend3/blend-dta-client#3]
## TODO
- [x] 초기 필요한 라이브러리 설치
* vite
* vitest
* react-router-dom
* tailwindcss
* react-query
* zustand
* axios
* prop-types
* react-icon
* joi

- [x] husky & eslint & prettier 환경 설정
- [x] 테스트 파일 작성
