### ISSUE TITLE
홈 화면 구성

### ISSUE THREAD

**Issue by hsj2955** [teamblend3/blend-dta-client#7]
## UI
<img width="1023" alt="스크린샷 2024-01-31 오후 7 08 27" src="https://github.com/teamblend3/blend-dta-client/assets/99715151/3ad5ae25-b0e3-4b6e-a3c0-132ca853dedb">
<br/>

## TODO
- [x] Mongo DB 로고, Google Spread Sheet Service 로고, 이 둘의 연동을 표현하는 이미지가 보여져야 한다.
- [x] 서비스명과 서비스에 대한 설명이 보여져야 한다.
- [x] Test 파일을 작성해야 한다.
